### ISSUE TITLE
Toolbar icon disappeared

### ISSUE THREAD

**Issue by ineuw** [cluclead/google-keep#3]
Hi,
Using FF beta in Xubuntu 16,04, in this FF 50.10b update, the Google Keep icon disappeared from the toolbar. I reinstalled it twice but it did not correct the issue, and the icon is not anywhere in the 'customize' window options.

**Comment by ineuw** [comment]
Please not that I just tested this issue with the identical FF version in Windows 7 and the toolbar icon was eliminated by the same beta update, Reinstalling in Windows 7 worked the icon is back. I hope that this helps.

P.S: I know that there are unnecessary differences between the Linux and Windows versions.

**Comment by ineuw** [comment]
In Linux, the icon does appear after reboot in the collection of the 'Customize" screen.

**Comment by ineuw** [comment]
Sorry, clicked on the wrong button

**Comment by cluclead** [comment]
I just pushed an update for FF 51 compatibility. Please wait until it gets approved. Then reopen if the issue persists on the new release.
